"""Low-overhead SiLU-and-multiply kernel for contiguous activations.

The layout is ``[..., 2 * d]`` with the gate in the first half and the value
in the second half. This mirrors the pointwise kernel generated by vLLM's
Inductor path for Qwen3.8, including its libdevice exponential and launch
configuration.
"""

import torch
import triton
import triton.language as tl
from triton.language.extra import libdevice


@triton.jit
def _silu_and_mul_kernel(
    x,
    out,
    output_width,
    input_width,
    numel,
    BLOCK: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < numel
    col = offsets % output_width
    row = offsets // output_width
    gate = tl.load(
        x + row * input_width + col,
        mask=mask,
        other=0.0,
        eviction_policy="evict_last",
    ).to(tl.float32)
    value = tl.load(
        x + row * input_width + output_width + col,
        mask=mask,
        other=0.0,
        eviction_policy="evict_last",
    ).to(tl.float32)
    activated = gate / (1.0 + libdevice.exp(-gate))
    tl.store(out + offsets, activated * value, mask=mask)


def silu_and_mul(out: torch.Tensor, x: torch.Tensor) -> None:
    """Write ``silu(x[..., :d]) * x[..., d:]`` into ``out``."""
    if x.shape[-1] % 2:
        raise ValueError(f"SiLU-and-mul input width must be even, got {x.shape}")
    output_width = x.shape[-1] // 2
    expected = x.shape[:-1] + (output_width,)
    if out.shape != expected:
        raise ValueError(f"SiLU-and-mul output shape must be {expected}, got {out.shape}")
    if x.dtype != out.dtype:
        raise ValueError(f"SiLU-and-mul dtype mismatch: {x.dtype} vs {out.dtype}")
    if x.dtype != torch.bfloat16:
        raise ValueError(
            f"SiLU-and-mul Triton fast path requires BF16, got {x.dtype}"
        )
    if not x.is_cuda or not out.is_cuda:
        raise ValueError("SiLU-and-mul Triton kernel requires CUDA tensors")
    if not x.is_contiguous() or not out.is_contiguous():
        raise ValueError("SiLU-and-mul Triton kernel requires contiguous tensors")

    numel = out.numel()
    if numel == 0:
        return
    block = 1024
    _silu_and_mul_kernel[(triton.cdiv(numel, block),)](
        x,
        out,
        output_width,
        x.shape[-1],
        numel,
        BLOCK=block,
        num_warps=4,
    )
